### PR TITLE
Fix application deadlock.

### PR DESCRIPTION
**Pull request by stephanemoore**
Fix application deadlock by asynchronously dispatching to the main queue in -[SNTAppDelegate createConnection].

### CODE REVIEW

**Comment by stephanemoore** [comment]
Regarding the CLA: I work for Google. My email is mog@google.com.

**Comment by x43x61x69** [comment]
Sorry, but it's way too funny to see what's happening above. :P

**Comment by ccaviness** [comment]
Thanks for the fix!

**Comment by russellhancox** [comment]
D'oh

**Pull request merged**
